"""Public key + constants for incremental update manifest verification.

The PUBLIC_KEY_HEX is the Ed25519 raw public key (32 bytes hex).
Generated by tools/gen_keys.py — keep the matching private key secret
and never commit it.

If the key is ever compromised, generate a new pair, replace this file,
release a new client version, and re-sign the manifest.
"""
from __future__ import annotations

PUBLIC_KEY_HEX = "d2bde2b171111965378f88752e4a3d443939cee951b664c47e0b205878eaf1e4"

MANIFEST_FILENAME = "manifest.json"
MANIFEST_SIG_FILENAME = "manifest.json.sig"
RELEASE_ZIP_FILENAME = "release.zip"

UPDATER_HEARTBEAT_FILENAME = ".update_heartbeat"
UPDATER_BACKUP_DIRNAME = ".update_backup"
UPDATER_STAGING_DIRNAME = ".update_staging"
UPDATER_LOG_FILENAME = ".update_log"
HEARTBEAT_TIMEOUT_SEC = 30
